export interface MedicineItem {
  id: string;
  name: string;
  form: string;
  formKey: string;
  category: string;
  categoryKey: string;
  manufacturer: string;
  country: string;
  dosage: string;
  availability: string[];
  price: number;
  rating: number;
  reviews: number;
  inStock: boolean;
  pharmaciesCount: number;
  distance: number; // in km
}

export const MEDICINE_CONFIG = {
  search: {
    placeholder: 'Назва ліків або діюча речовина...',
  },
  sorts: [
    { value: 'relevance', label: 'За релевантністю' },
    { value: 'popular', label: 'За популярністю' },
    { value: 'price_asc', label: 'Найдешевші' },
    { value: 'price_desc', label: 'Найдорожчі' },
    { value: 'rating', label: 'Найвищий рейтинг' },
    { value: 'nearest', label: 'Найближчі' },
    { value: 'alphabet', label: 'За алфавітом' },
  ],
  filters: [
    {
      id: 'categoryKey',
      label: 'Категорія',
      type: 'searchable-select',
      options: [
        { value: 'all', label: 'Всі категорії' },
        { value: 'painkillers', label: 'Знеболювальні' },
        { value: 'antibiotics', label: 'Антибіотики' },
        { value: 'vitamins', label: 'Вітаміни' },
        { value: 'flu', label: 'Застуда та грип' },
        { value: 'allergy', label: 'Алергія' },
        { value: 'cardiology', label: 'Серцево-судинні' },
        { value: 'gastro', label: 'Гастроентерологія' },
      ],
    },
    {
      id: 'availability',
      label: 'Наявність',
      type: 'select',
      options: [
        { value: 'all', label: 'Усі варіанти' },
        { value: 'in_stock', label: 'В наявності зараз' },
        { value: 'nearby', label: 'Поруч із вами' },
        { value: 'bookable', label: 'Можна забронювати' },
        { value: 'prescription', label: 'За рецептом' },
        { value: 'over_counter', label: 'Без рецепту' },
      ],
    },
    {
      id: 'price',
      label: 'Ціна',
      type: 'slider-range',
      minKey: 'priceMin',
      maxKey: 'priceMax',
      min: 0,
      max: 1000,
    },
    {
      id: 'manufacturer',
      label: 'Виробник',
      type: 'searchable-select',
      options: [
        { value: 'all', label: 'Усі виробники' },
        { value: 'Reckitt', label: 'Reckitt' },
        { value: 'Pharmak', label: 'Фармак' },
        { value: 'Kusum', label: 'Кусум' },
        { value: 'KRKA', label: 'КРКА' },
        { value: 'Berlin-Chemie', label: 'Berlin-Chemie' },
        { value: 'NOW', label: 'NOW' },
        { value: 'Sanofi', label: 'Sanofi' },
      ],
    },
    {
      id: 'country',
      label: 'Країна виробництва',
      type: 'searchable-select',
      options: [
        { value: 'all', label: 'Усі країни' },
        { value: 'Ukraine', label: 'Україна' },
        { value: 'Germany', label: 'Німеччина' },
        { value: 'France', label: 'Франція' },
        { value: 'USA', label: 'США' },
        { value: 'India', label: 'Індія' },
        { value: 'UK', label: 'Велика Британія' },
        { value: 'Slovenia', label: 'Словенія' },
      ],
    },
    {
      id: 'formKey',
      label: 'Форма випуску',
      type: 'searchable-select',
      options: [
        { value: 'all', label: 'Усі форми' },
        { value: 'tablets', label: 'Таблетки' },
        { value: 'capsules', label: 'Капсули' },
        { value: 'syrup', label: 'Сироп' },
        { value: 'injection', label: 'Ін\'єкції' },
        { value: 'cream', label: 'Крем' },
        { value: 'gel', label: 'Гель' },
        { value: 'spray', label: 'Спрей' },
      ],
    },
    {
      id: 'dosage',
      label: 'Дозування',
      type: 'searchable-select',
      options: [
        { value: 'all', label: 'Усі дозування' },
        { value: '5mg', label: '5 мг' },
        { value: '10mg', label: '10 мг' },
        { value: '50mg', label: '50 мг' },
        { value: '100mg', label: '100 мг' },
        { value: '200mg', label: '200 мг' },
      ],
    },
  ],
};

export function getMedicineConfig(t: any) {
  return {
    search: {
      placeholder: t('search.medicines'),
    },
    sorts: [
      { value: 'relevance', label: t('sorts.relevance') },
      { value: 'popular', label: t('sorts.popular') },
      { value: 'price_asc', label: t('sorts.price_asc') },
      { value: 'price_desc', label: t('sorts.price_desc') },
      { value: 'rating', label: t('sorts.rating') },
      { value: 'nearest', label: t('sorts.nearest') },
      { value: 'alphabet', label: t('sorts.alphabet') },
    ],
    filters: [
      {
        id: 'categoryKey',
        label: t('filterLabels.category'),
        type: 'searchable-select',
        options: [
          { value: 'all', label: t('options.category.all') },
          { value: 'painkillers', label: t('options.category.painkillers') },
          { value: 'antibiotics', label: t('options.category.antibiotics') },
          { value: 'vitamins', label: t('options.category.vitamins') },
          { value: 'flu', label: t('options.category.flu') },
          { value: 'allergy', label: t('options.category.allergy') },
          { value: 'cardiology', label: t('options.category.cardiology') },
          { value: 'gastro', label: t('options.category.gastro') },
        ],
      },
      {
        id: 'availability',
        label: t('filterLabels.availability'),
        type: 'select',
        options: [
          { value: 'all', label: t('options.availability.all') },
          { value: 'in_stock', label: t('options.availability.in_stock') },
          { value: 'nearby', label: t('options.availability.nearby') },
          { value: 'bookable', label: t('options.availability.bookable') },
          { value: 'prescription', label: t('options.availability.prescription') },
          { value: 'over_counter', label: t('options.availability.over_counter') },
        ],
      },
      {
        id: 'price',
        label: t('filterLabels.price'),
        type: 'slider-range',
        minKey: 'priceMin',
        maxKey: 'priceMax',
        min: 0,
        max: 1000,
      },
      {
        id: 'manufacturer',
        label: t('filterLabels.manufacturer'),
        type: 'searchable-select',
        options: [
          { value: 'all', label: t('options.manufacturer.all') },
          { value: 'Reckitt', label: 'Reckitt' },
          { value: 'Pharmak', label: 'Pharmak' },
          { value: 'Kusum', label: 'Kusum' },
          { value: 'KRKA', label: 'KRKA' },
          { value: 'Berlin-Chemie', label: 'Berlin-Chemie' },
          { value: 'NOW', label: 'NOW' },
          { value: 'Sanofi', label: 'Sanofi' },
        ],
      },
      {
        id: 'country',
        label: t('filterLabels.country'),
        type: 'searchable-select',
        options: [
          { value: 'all', label: t('options.country.all') },
          { value: 'Ukraine', label: t('options.country.Ukraine') },
          { value: 'Germany', label: t('options.country.Germany') },
          { value: 'France', label: t('options.country.France') },
          { value: 'USA', label: t('options.country.USA') },
          { value: 'India', label: t('options.country.India') },
          { value: 'UK', label: t('options.country.UK') },
          { value: 'Slovenia', label: t('options.country.Slovenia') },
        ],
      },
      {
        id: 'formKey',
        label: t('filterLabels.form'),
        type: 'searchable-select',
        options: [
          { value: 'all', label: t('options.form.all') },
          { value: 'tablets', label: t('options.form.tablets') },
          { value: 'capsules', label: t('options.form.capsules') },
          { value: 'syrup', label: t('options.form.syrup') },
          { value: 'injection', label: t('options.form.injection') },
          { value: 'cream', label: t('options.form.cream') },
          { value: 'gel', label: t('options.form.gel') },
          { value: 'spray', label: t('options.form.spray') },
        ],
      },
      {
        id: 'dosage',
        label: t('filterLabels.dosage'),
        type: 'searchable-select',
        options: [
          { value: 'all', label: t('options.dosage.all') },
          { value: '5mg', label: '5 мг' },
          { value: '10mg', label: '10 мг' },
          { value: '50mg', label: '50 мг' },
          { value: '100mg', label: '100 мг' },
          { value: '200mg', label: '200 мг' },
        ],
      },
    ],
  };
}

export function getMedicines(t: any): MedicineItem[] {
  return MEDICINES.map((item) => ({
    ...item,
    name: t(`items.medicines.${item.id}.name`),
    form: t(`items.medicines.${item.id}.form`),
    category: t(`items.medicines.${item.id}.category`),
  }));
}

export const MEDICINES: MedicineItem[] = [
  {
    id: 'nurofen',
    name: 'Нурофен Express',
    form: 'Таблетки, 200 мг, №24',
    formKey: 'tablets',
    category: 'Знеболювальні',
    categoryKey: 'painkillers',
    manufacturer: 'Reckitt',
    country: 'UK',
    dosage: '200mg',
    availability: ['in_stock', 'nearby', 'bookable', 'over_counter'],
    price: 89,
    rating: 4.8,
    reviews: 328,
    inStock: true,
    pharmaciesCount: 214,
    distance: 0.4,
  },
  {
    id: 'paracetamol',
    name: 'Парацетамол-Дарниця',
    form: 'Таблетки, 500 мг, №10',
    formKey: 'tablets',
    category: 'Знеболювальні',
    categoryKey: 'painkillers',
    manufacturer: 'Pharmak',
    country: 'Ukraine',
    dosage: '50mg',
    availability: ['in_stock', 'nearby', 'bookable', 'over_counter'],
    price: 24,
    rating: 4.5,
    reviews: 120,
    inStock: true,
    pharmaciesCount: 356,
    distance: 0.8,
  },
  {
    id: 'amoxil',
    name: 'Амоксил',
    form: 'Капсули, 500 мг, №20',
    formKey: 'capsules',
    category: 'Антибіотики',
    categoryKey: 'antibiotics',
    manufacturer: 'Pharmak',
    country: 'Ukraine',
    dosage: '100mg',
    availability: ['in_stock', 'bookable', 'prescription'],
    price: 132,
    rating: 4.7,
    reviews: 85,
    inStock: true,
    pharmaciesCount: 178,
    distance: 1.2,
  },
  {
    id: 'vitaminD3',
    name: 'Аквадетрим Вітамін D3',
    form: 'Краплі, 4000 МО, 10 мл',
    formKey: 'syrup',
    category: 'Вітаміни',
    categoryKey: 'vitamins',
    manufacturer: 'Berlin-Chemie',
    country: 'Germany',
    dosage: '10mg',
    availability: ['in_stock', 'nearby', 'bookable', 'over_counter'],
    price: 215,
    rating: 4.9,
    reviews: 412,
    inStock: true,
    pharmaciesCount: 142,
    distance: 0.5,
  },
  {
    id: 'analgin',
    name: 'Анальгін-Здоров’я',
    form: 'Таблетки, 500 мг, №10',
    formKey: 'tablets',
    category: 'Знеболювальні',
    categoryKey: 'painkillers',
    manufacturer: 'Kusum',
    country: 'Ukraine',
    dosage: '50mg',
    availability: ['over_counter'],
    price: 18,
    rating: 4.2,
    reviews: 90,
    inStock: false,
    pharmaciesCount: 0,
    distance: 3.5,
  },
  {
    id: 'aspirin',
    name: 'Аспірин Кардіо',
    form: 'Таблетки, 100 мг, №28',
    formKey: 'tablets',
    category: 'Серцево-судинні',
    categoryKey: 'cardiology',
    manufacturer: 'Sanofi',
    country: 'France',
    dosage: '100mg',
    availability: ['in_stock', 'nearby', 'bookable', 'over_counter'],
    price: 65,
    rating: 4.6,
    reviews: 194,
    inStock: true,
    pharmaciesCount: 280,
    distance: 0.9,
  },
  {
    id: 'ascorbic',
    name: 'Вітамін C (Аскорбінка)',
    form: 'Драже, 50 мг, №50',
    formKey: 'tablets',
    category: 'Вітаміни',
    categoryKey: 'vitamins',
    manufacturer: 'NOW',
    country: 'USA',
    dosage: '50mg',
    availability: ['in_stock', 'nearby', 'bookable', 'over_counter'],
    price: 15,
    rating: 4.7,
    reviews: 210,
    inStock: true,
    pharmaciesCount: 420,
    distance: 0.3,
  },
  {
    id: 'suprastin',
    name: 'Супрастин',
    form: 'Таблетки, 25 мг, №20',
    formKey: 'tablets',
    category: 'Алергія',
    categoryKey: 'allergy',
    manufacturer: 'KRKA',
    country: 'Slovenia',
    dosage: '5mg',
    availability: ['in_stock', 'bookable', 'over_counter'],
    price: 110,
    rating: 4.5,
    reviews: 74,
    inStock: true,
    pharmaciesCount: 165,
    distance: 1.5,
  },
  {
    id: 'loratadine',
    name: 'Лоратадин-Здоров’я',
    form: 'Таблетки, 10 мг, №10',
    formKey: 'tablets',
    category: 'Алергія',
    categoryKey: 'allergy',
    manufacturer: 'Pharmak',
    country: 'Ukraine',
    dosage: '10mg',
    availability: ['in_stock', 'nearby', 'bookable', 'over_counter'],
    price: 35,
    rating: 4.3,
    reviews: 104,
    inStock: true,
    pharmaciesCount: 230,
    distance: 0.7,
  },
];
